### PR TITLE
Embedding fonts, adding renders, some dressing up.

### PR DESCRIPTION
**Pull request by bgillespie**
* Used free font "Alfa Slab One" for logo text, which is the same
  font rust-lang.org uses.
* Used "Noto Serif" font for title and author/speaker on YouTube
  template.
* Tarted up YouTube template a bit. Uses Rust Dublin "cog" logo.
* Simplified structure of main logo by doing a union on some of the
  constituent shapes.
* Added PNGs of the artwork in `renders` folder so that you don't
  have to install the fonts to see the artwork as intended.

### CODE REVIEW

**Comment by bgillespie** [comment]
I've been doing edits to the videos. I've almost finished one of them, just got to do the front banner and before I do wanted to run these by you all. They're just suggestions, of course: if you'd rather no changes I won't mind :-)

There are PNGs in the `renders` folder but if you are able to load the YouTube banner into Inkscape you can see alternatives by showing/hiding layers.

Cheers
bri

**Comment by ekarademir** [comment]
Just for completeness, maybe add to README file and explain that the fonts need to be installed before editing? Otherwise we should always outline the fonts in the SVG files so that they can be used without any editing.

**Comment by codecrunchers** [comment]
Looks good  Brian, the consistency will look good over time

**Review by codecrunchers — APPROVED** [review]

**Comment by codecrunchers** [comment]
@bgillespie  I was thinking of adding a list of social media icons to the bottom of the YouTube Splash

[BLOG] [CHAT] [GIT] [MEETUP]  (using a free icon set like https://iconmonstr.com/iconicfont/ or similar)

etc...
any thoughts?

**Comment by bgillespie** [comment]
> @bgillespie I was thinking of adding a list of social media icons to the bottom of the YouTube Splash
> [BLOG] [CHAT] [GIT] [MEETUP] (using a free icon set like https://iconmonstr.com/iconicfont/ or similar)

Yeah that'd work. They might have to be quite small to fit in (I haven't tried it though) but watchers could always pause the video to get the deets.

**Comment by ekarademir** [comment]
Sorry for being a nuisance @bgillespie but could you use Git LFS (https://git-lfs.github.com/) for tracking ZIP files and PNG files please? Otherwise we will need to track a lot of unnecessary changes. Apologies if you have already done that, in which case we should also indicate that in the README.

**Comment by bgillespie** [comment]
I didn't use that, or at least not that I know of. I'll look into that -
cheers 👍

**Comment by bgillespie** [comment]
Has that done it, @ekarademir? I've not used git-lfs before, I'm not sure what I'm expecting to see.

**Review by ekarademir — APPROVED** [review]

**Comment by ekarademir** [comment]
Thank you @bgillespie Not much should change, it will just keep the last binary you've added to the repo instead of keeping each version. Since git won't diff the binary, they would add up in git history. Probably overkill in this repo but never-the-less, it's a good practice.

**Comment by ekarademir** [comment]
You should be able to merge this @bgillespie if not let me know and I will try to change the settings.

**Pull request merged**
